"""Checkpoint loading helpers for trusted Matcha-TTS assets.

PyTorch 2.6 changed ``torch.load`` to default to ``weights_only=True``. The
public Matcha-TTS Lightning checkpoints include Hydra/OmegaConf objects in their
metadata, so they must be loaded with ``weights_only=False``. Only use these
helpers for checkpoints from trusted sources, such as checkpoints generated by
this project or the official Matcha-TTS checkpoint URLs.
"""

import inspect
from typing import Any

import torch


def _accepts_kwarg(callable_obj: Any, kwarg_name: str) -> bool:
    """Return whether ``callable_obj`` exposes ``kwarg_name`` in its signature."""
    return kwarg_name in inspect.signature(callable_obj).parameters


def torch_load_trusted(checkpoint_path, map_location=None):
    """Load a trusted PyTorch checkpoint across PyTorch versions."""
    kwargs = {"map_location": map_location}
    if _accepts_kwarg(torch.load, "weights_only"):
        kwargs["weights_only"] = False
    return torch.load(checkpoint_path, **kwargs)


def load_lightning_checkpoint_trusted(model_cls, checkpoint_path, map_location=None):
    """Load a trusted Lightning checkpoint across Lightning/PyTorch versions."""
    kwargs = {"map_location": map_location}
    if _accepts_kwarg(model_cls.load_from_checkpoint, "weights_only"):
        kwargs["weights_only"] = False
    return model_cls.load_from_checkpoint(checkpoint_path, **kwargs)
